//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Sensor
{
    [Serializable]
    public class SetCameraInfo_ResponseMsg : Message
    {
        public const string k_RosMessageName = "sensor_msgs/SetCameraInfo_Response";
        public override string RosMessageName => k_RosMessageName;

        public bool success;
        //  True if the call succeeded
        public string status_message;
        //  Used to give details about success

        public SetCameraInfo_ResponseMsg()
        {
            this.success = false;
            this.status_message = "";
        }

        public SetCameraInfo_ResponseMsg(bool success, string status_message)
        {
            this.success = success;
            this.status_message = status_message;
        }

        public static SetCameraInfo_ResponseMsg Deserialize(MessageDeserializer deserializer) => new SetCameraInfo_ResponseMsg(deserializer);

        private SetCameraInfo_ResponseMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.success);
            deserializer.Read(out this.status_message);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.success);
            serializer.Write(this.status_message);
        }

        public override string ToString()
        {
            return "SetCameraInfo_ResponseMsg: " +
            "\nsuccess: " + success.ToString() +
            "\nstatus_message: " + status_message.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
