//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Moveit
{
    [Serializable]
    public class CheckIfRobotStateExistsInWarehouse_ResponseMsg : Message
    {
        public const string k_RosMessageName = "moveit_msgs/CheckIfRobotStateExistsInWarehouse_Response";
        public override string RosMessageName => k_RosMessageName;

        public bool exists;

        public CheckIfRobotStateExistsInWarehouse_ResponseMsg()
        {
            this.exists = false;
        }

        public CheckIfRobotStateExistsInWarehouse_ResponseMsg(bool exists)
        {
            this.exists = exists;
        }

        public static CheckIfRobotStateExistsInWarehouse_ResponseMsg Deserialize(MessageDeserializer deserializer) => new CheckIfRobotStateExistsInWarehouse_ResponseMsg(deserializer);

        private CheckIfRobotStateExistsInWarehouse_ResponseMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.exists);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.exists);
        }

        public override string ToString()
        {
            return "CheckIfRobotStateExistsInWarehouse_ResponseMsg: " +
            "\nexists: " + exists.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
