//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Moveit
{
    [Serializable]
    public class DeleteRobotStateFromWarehouse_RequestMsg : Message
    {
        public const string k_RosMessageName = "moveit_msgs/DeleteRobotStateFromWarehouse_Request";
        public override string RosMessageName => k_RosMessageName;

        public string name;
        public string robot;

        public DeleteRobotStateFromWarehouse_RequestMsg()
        {
            this.name = "";
            this.robot = "";
        }

        public DeleteRobotStateFromWarehouse_RequestMsg(string name, string robot)
        {
            this.name = name;
            this.robot = robot;
        }

        public static DeleteRobotStateFromWarehouse_RequestMsg Deserialize(MessageDeserializer deserializer) => new DeleteRobotStateFromWarehouse_RequestMsg(deserializer);

        private DeleteRobotStateFromWarehouse_RequestMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.name);
            deserializer.Read(out this.robot);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.name);
            serializer.Write(this.robot);
        }

        public override string ToString()
        {
            return "DeleteRobotStateFromWarehouse_RequestMsg: " +
            "\nname: " + name.ToString() +
            "\nrobot: " + robot.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
