//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Moveit
{
    [Serializable]
    public class ExecuteKnownTrajectory_ResponseMsg : Message
    {
        public const string k_RosMessageName = "moveit_msgs/ExecuteKnownTrajectory_Response";
        public override string RosMessageName => k_RosMessageName;

        //  Error code - encodes the overall reason for failure
        public MoveItErrorCodesMsg error_code;

        public ExecuteKnownTrajectory_ResponseMsg()
        {
            this.error_code = new MoveItErrorCodesMsg();
        }

        public ExecuteKnownTrajectory_ResponseMsg(MoveItErrorCodesMsg error_code)
        {
            this.error_code = error_code;
        }

        public static ExecuteKnownTrajectory_ResponseMsg Deserialize(MessageDeserializer deserializer) => new ExecuteKnownTrajectory_ResponseMsg(deserializer);

        private ExecuteKnownTrajectory_ResponseMsg(MessageDeserializer deserializer)
        {
            this.error_code = MoveItErrorCodesMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.error_code);
        }

        public override string ToString()
        {
            return "ExecuteKnownTrajectory_ResponseMsg: " +
            "\nerror_code: " + error_code.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
