//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Moveit
{
    [Serializable]
    public class GetMotionSequence_RequestMsg : Message
    {
        public const string k_RosMessageName = "moveit_msgs/GetMotionSequence_Request";
        public override string RosMessageName => k_RosMessageName;

        //  Planning request with a list of motion commands
        public MotionSequenceRequestMsg request;

        public GetMotionSequence_RequestMsg()
        {
            this.request = new MotionSequenceRequestMsg();
        }

        public GetMotionSequence_RequestMsg(MotionSequenceRequestMsg request)
        {
            this.request = request;
        }

        public static GetMotionSequence_RequestMsg Deserialize(MessageDeserializer deserializer) => new GetMotionSequence_RequestMsg(deserializer);

        private GetMotionSequence_RequestMsg(MessageDeserializer deserializer)
        {
            this.request = MotionSequenceRequestMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.request);
        }

        public override string ToString()
        {
            return "GetMotionSequence_RequestMsg: " +
            "\nrequest: " + request.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
