//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Moveit
{
    [Serializable]
    public class GetMotionSequence_ResponseMsg : Message
    {
        public const string k_RosMessageName = "moveit_msgs/GetMotionSequence_Response";
        public override string RosMessageName => k_RosMessageName;

        //  Response to the planning request
        public MotionSequenceResponseMsg response;

        public GetMotionSequence_ResponseMsg()
        {
            this.response = new MotionSequenceResponseMsg();
        }

        public GetMotionSequence_ResponseMsg(MotionSequenceResponseMsg response)
        {
            this.response = response;
        }

        public static GetMotionSequence_ResponseMsg Deserialize(MessageDeserializer deserializer) => new GetMotionSequence_ResponseMsg(deserializer);

        private GetMotionSequence_ResponseMsg(MessageDeserializer deserializer)
        {
            this.response = MotionSequenceResponseMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.response);
        }

        public override string ToString()
        {
            return "GetMotionSequence_ResponseMsg: " +
            "\nresponse: " + response.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
