//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Moveit
{
    [Serializable]
    public class GetPlannerParams_ResponseMsg : Message
    {
        public const string k_RosMessageName = "moveit_msgs/GetPlannerParams_Response";
        public override string RosMessageName => k_RosMessageName;

        //  parameters as key-value pairs
        public PlannerParamsMsg @params;

        public GetPlannerParams_ResponseMsg()
        {
            this.@params = new PlannerParamsMsg();
        }

        public GetPlannerParams_ResponseMsg(PlannerParamsMsg @params)
        {
            this.@params = @params;
        }

        public static GetPlannerParams_ResponseMsg Deserialize(MessageDeserializer deserializer) => new GetPlannerParams_ResponseMsg(deserializer);

        private GetPlannerParams_ResponseMsg(MessageDeserializer deserializer)
        {
            this.@params = PlannerParamsMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.@params);
        }

        public override string ToString()
        {
            return "GetPlannerParams_ResponseMsg: " +
            "\n@params: " + @params.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
