//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Moveit
{
    [Serializable]
    public class GetPlanningScene_ResponseMsg : Message
    {
        public const string k_RosMessageName = "moveit_msgs/GetPlanningScene_Response";
        public override string RosMessageName => k_RosMessageName;

        public PlanningSceneMsg scene;

        public GetPlanningScene_ResponseMsg()
        {
            this.scene = new PlanningSceneMsg();
        }

        public GetPlanningScene_ResponseMsg(PlanningSceneMsg scene)
        {
            this.scene = scene;
        }

        public static GetPlanningScene_ResponseMsg Deserialize(MessageDeserializer deserializer) => new GetPlanningScene_ResponseMsg(deserializer);

        private GetPlanningScene_ResponseMsg(MessageDeserializer deserializer)
        {
            this.scene = PlanningSceneMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.scene);
        }

        public override string ToString()
        {
            return "GetPlanningScene_ResponseMsg: " +
            "\nscene: " + scene.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
