//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Moveit
{
    [Serializable]
    public class GetPlanningScene_RequestMsg : Message
    {
        public const string k_RosMessageName = "moveit_msgs/GetPlanningScene_Request";
        public override string RosMessageName => k_RosMessageName;

        //  Get parts of the planning scene that are of interest
        //  All scene components are returned if none are specified
        public PlanningSceneComponentsMsg components;

        public GetPlanningScene_RequestMsg()
        {
            this.components = new PlanningSceneComponentsMsg();
        }

        public GetPlanningScene_RequestMsg(PlanningSceneComponentsMsg components)
        {
            this.components = components;
        }

        public static GetPlanningScene_RequestMsg Deserialize(MessageDeserializer deserializer) => new GetPlanningScene_RequestMsg(deserializer);

        private GetPlanningScene_RequestMsg(MessageDeserializer deserializer)
        {
            this.components = PlanningSceneComponentsMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.components);
        }

        public override string ToString()
        {
            return "GetPlanningScene_RequestMsg: " +
            "\ncomponents: " + components.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
