//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Moveit
{
    [Serializable]
    public class GetRobotStateFromWarehouse_ResponseMsg : Message
    {
        public const string k_RosMessageName = "moveit_msgs/GetRobotStateFromWarehouse_Response";
        public override string RosMessageName => k_RosMessageName;

        public RobotStateMsg state;

        public GetRobotStateFromWarehouse_ResponseMsg()
        {
            this.state = new RobotStateMsg();
        }

        public GetRobotStateFromWarehouse_ResponseMsg(RobotStateMsg state)
        {
            this.state = state;
        }

        public static GetRobotStateFromWarehouse_ResponseMsg Deserialize(MessageDeserializer deserializer) => new GetRobotStateFromWarehouse_ResponseMsg(deserializer);

        private GetRobotStateFromWarehouse_ResponseMsg(MessageDeserializer deserializer)
        {
            this.state = RobotStateMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.state);
        }

        public override string ToString()
        {
            return "GetRobotStateFromWarehouse_ResponseMsg: " +
            "\nstate: " + state.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
