//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Moveit
{
    [Serializable]
    public class GraspPlanning_ResponseMsg : Message
    {
        public const string k_RosMessageName = "moveit_msgs/GraspPlanning_Response";
        public override string RosMessageName => k_RosMessageName;

        //  the list of planned grasps
        public GraspMsg[] grasps;
        //  whether an error occurred
        public MoveItErrorCodesMsg error_code;

        public GraspPlanning_ResponseMsg()
        {
            this.grasps = new GraspMsg[0];
            this.error_code = new MoveItErrorCodesMsg();
        }

        public GraspPlanning_ResponseMsg(GraspMsg[] grasps, MoveItErrorCodesMsg error_code)
        {
            this.grasps = grasps;
            this.error_code = error_code;
        }

        public static GraspPlanning_ResponseMsg Deserialize(MessageDeserializer deserializer) => new GraspPlanning_ResponseMsg(deserializer);

        private GraspPlanning_ResponseMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.grasps, GraspMsg.Deserialize, deserializer.ReadLength());
            this.error_code = MoveItErrorCodesMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.WriteLength(this.grasps);
            serializer.Write(this.grasps);
            serializer.Write(this.error_code);
        }

        public override string ToString()
        {
            return "GraspPlanning_ResponseMsg: " +
            "\ngrasps: " + System.String.Join(", ", grasps.ToList()) +
            "\nerror_code: " + error_code.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
