//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Moveit
{
    [Serializable]
    public class ListRobotStatesInWarehouse_ResponseMsg : Message
    {
        public const string k_RosMessageName = "moveit_msgs/ListRobotStatesInWarehouse_Response";
        public override string RosMessageName => k_RosMessageName;

        public string[] states;

        public ListRobotStatesInWarehouse_ResponseMsg()
        {
            this.states = new string[0];
        }

        public ListRobotStatesInWarehouse_ResponseMsg(string[] states)
        {
            this.states = states;
        }

        public static ListRobotStatesInWarehouse_ResponseMsg Deserialize(MessageDeserializer deserializer) => new ListRobotStatesInWarehouse_ResponseMsg(deserializer);

        private ListRobotStatesInWarehouse_ResponseMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.states, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.WriteLength(this.states);
            serializer.Write(this.states);
        }

        public override string ToString()
        {
            return "ListRobotStatesInWarehouse_ResponseMsg: " +
            "\nstates: " + System.String.Join(", ", states.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
