//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Moveit
{
    [Serializable]
    public class ListRobotStatesInWarehouse_RequestMsg : Message
    {
        public const string k_RosMessageName = "moveit_msgs/ListRobotStatesInWarehouse_Request";
        public override string RosMessageName => k_RosMessageName;

        public string regex;
        public string robot;

        public ListRobotStatesInWarehouse_RequestMsg()
        {
            this.regex = "";
            this.robot = "";
        }

        public ListRobotStatesInWarehouse_RequestMsg(string regex, string robot)
        {
            this.regex = regex;
            this.robot = robot;
        }

        public static ListRobotStatesInWarehouse_RequestMsg Deserialize(MessageDeserializer deserializer) => new ListRobotStatesInWarehouse_RequestMsg(deserializer);

        private ListRobotStatesInWarehouse_RequestMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.regex);
            deserializer.Read(out this.robot);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.regex);
            serializer.Write(this.robot);
        }

        public override string ToString()
        {
            return "ListRobotStatesInWarehouse_RequestMsg: " +
            "\nregex: " + regex.ToString() +
            "\nrobot: " + robot.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
