//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Moveit
{
    [Serializable]
    public class QueryPlannerInterfaces_RequestMsg : Message
    {
        public const string k_RosMessageName = "moveit_msgs/QueryPlannerInterfaces_Request";
        public override string RosMessageName => k_RosMessageName;


        public QueryPlannerInterfaces_RequestMsg()
        {
        }
        public static QueryPlannerInterfaces_RequestMsg Deserialize(MessageDeserializer deserializer) => new QueryPlannerInterfaces_RequestMsg(deserializer);

        private QueryPlannerInterfaces_RequestMsg(MessageDeserializer deserializer)
        {
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
        }

        public override string ToString()
        {
            return "QueryPlannerInterfaces_RequestMsg: ";
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
