//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Moveit
{
    [Serializable]
    public class SaveMap_RequestMsg : Message
    {
        public const string k_RosMessageName = "moveit_msgs/SaveMap_Request";
        public override string RosMessageName => k_RosMessageName;

        public string filename;

        public SaveMap_RequestMsg()
        {
            this.filename = "";
        }

        public SaveMap_RequestMsg(string filename)
        {
            this.filename = filename;
        }

        public static SaveMap_RequestMsg Deserialize(MessageDeserializer deserializer) => new SaveMap_RequestMsg(deserializer);

        private SaveMap_RequestMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.filename);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.filename);
        }

        public override string ToString()
        {
            return "SaveMap_RequestMsg: " +
            "\nfilename: " + filename.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
