//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Moveit
{
    [Serializable]
    public class SetPlannerParams_ResponseMsg : Message
    {
        public const string k_RosMessageName = "moveit_msgs/SetPlannerParams_Response";
        public override string RosMessageName => k_RosMessageName;


        public SetPlannerParams_ResponseMsg()
        {
        }
        public static SetPlannerParams_ResponseMsg Deserialize(MessageDeserializer deserializer) => new SetPlannerParams_ResponseMsg(deserializer);

        private SetPlannerParams_ResponseMsg(MessageDeserializer deserializer)
        {
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
        }

        public override string ToString()
        {
            return "SetPlannerParams_ResponseMsg: ";
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
