//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Moveit
{
    [Serializable]
    public class UpdatePointcloudOctomap_RequestMsg : Message
    {
        public const string k_RosMessageName = "moveit_msgs/UpdatePointcloudOctomap_Request";
        public override string RosMessageName => k_RosMessageName;

        public Sensor.PointCloud2Msg cloud;

        public UpdatePointcloudOctomap_RequestMsg()
        {
            this.cloud = new Sensor.PointCloud2Msg();
        }

        public UpdatePointcloudOctomap_RequestMsg(Sensor.PointCloud2Msg cloud)
        {
            this.cloud = cloud;
        }

        public static UpdatePointcloudOctomap_RequestMsg Deserialize(MessageDeserializer deserializer) => new UpdatePointcloudOctomap_RequestMsg(deserializer);

        private UpdatePointcloudOctomap_RequestMsg(MessageDeserializer deserializer)
        {
            this.cloud = Sensor.PointCloud2Msg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.cloud);
        }

        public override string ToString()
        {
            return "UpdatePointcloudOctomap_RequestMsg: " +
            "\ncloud: " + cloud.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
