//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Moveit
{
    [Serializable]
    public class UpdatePointcloudOctomap_ResponseMsg : Message
    {
        public const string k_RosMessageName = "moveit_msgs/UpdatePointcloudOctomap_Response";
        public override string RosMessageName => k_RosMessageName;

        public bool success;

        public UpdatePointcloudOctomap_ResponseMsg()
        {
            this.success = false;
        }

        public UpdatePointcloudOctomap_ResponseMsg(bool success)
        {
            this.success = success;
        }

        public static UpdatePointcloudOctomap_ResponseMsg Deserialize(MessageDeserializer deserializer) => new UpdatePointcloudOctomap_ResponseMsg(deserializer);

        private UpdatePointcloudOctomap_ResponseMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.success);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.success);
        }

        public override string ToString()
        {
            return "UpdatePointcloudOctomap_ResponseMsg: " +
            "\nsuccess: " + success.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
